### ISSUE TITLE
Partners

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#10]
As a user i want to know what services are used in providing this product.

This is the fourth section of the home page and should contain the 3 partners of the product.

Changelly, Nav Coin & NavTech.

These will be styled much like the Nav Coin website.

Each icon includes:

- [ ] Circle Icon
- [ ] Heading
- [ ] 2 lines of text

These should be clickable tiles rather than free floating. They should link to the partners site.

These should be laid out in 3 columns which collapses to 1 column for small devices.

**Comment by matt-auckland** [comment]
blocked due to rewriting of #24 to modularise the whole 'image w text' thing
