### ISSUE TITLE
API End Points Santitization & Checking

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#133]
All endpoints should validate the data parsed to them. 

Check that all the expected params are present.

Optional: Check that all the parsed params are of the expected type.

Endpoints

* [x] ChangellyCtrl.getCurrencies
* [x] ChangellyCtrl.getMinAmount
* [x] ChangellyCtrl.getExchangeAmount
* [x] ChangellyCtrl.generateAddress
* [x] EtaCtrl.generateEstimate
* [x] OrderCtrl.createOrder
* [x] OrderStatusCtrl.getOrder
* [x] OrderStatusCtrl.updateOrderStatus
* [x] OrderStatusCtrl.abandonOrder

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"ped":"2017-10-02T20:00:00+13:00"})

**Comment by craigmacgregor** [comment]
Investigate whether complex type definitions can be simply implemented, look for typedef plugins and talk to me to decide if we do simple required checks or type of checks.

**Comment by matt-auckland** [comment]
https://github.com/chriso/validator.js
This seems like a decent plugin to use
