### ISSUE TITLE
Polymorph Staging Site

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#159]
- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-13T09:00:00+13:00","ped":"2017-11-17T18:00:00+13:00"})

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

https://polymorph.navcoin.org:3000

needs this header editor plugin: 

https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj

import config:

{"title":"Polymorph","hideComment":true,"headers":[{"enabled":true,"name":"Authorization","value":"Basic c3RhZ2luZzoyelpyVVRJSm9rMll0Y0xOT1BkSlBwZU4=","comment":""}],"respHeaders":[],"filters":[],"appendMode":""}
