### ISSUE TITLE
Header Navigation

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#3]
Create the main navigation for the site. 

Design reference is the tabs component header.

Should appear on all pages.

Navigation should be sticky to the top of the page.

Collapse down to hamburger menu on mobile. Clicking hamburger brings in sidenav component with main navigation menu in it.

Items are:

- [ ] Home
- [ ] Send
- [ ] About
- [ ] Contact

Logo should also appear on the header and link to the home page.

Need to fix the sidenav bug: it doesn't close when you click a link. 

To Do:

- [x] Set up navbar w/ items
- [x] Fix any styling
- [x] Fix sidenav bug

**Comment by matt-auckland** [comment]
"Top of the page" meaning fixed to the top of the browser window?
