### ISSUE TITLE
Style Support Desk

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#54]
Style the support desk page to be in line with Polymorph branding.

**Comment by matt-auckland** [comment]
Need a logo to upload

**Comment by matt-auckland** [comment]
Logo added.

**Comment by matt-auckland** [comment]
## Style Preview 
![image](https://cloud.githubusercontent.com/assets/12672050/26568208/9123e046-4555-11e7-934d-7b7fc71f9d04.png)

![image](https://cloud.githubusercontent.com/assets/12672050/26568228/cd83a3d2-4555-11e7-9827-adf34548d0db.png)

**Comment by matt-auckland** [comment]
There seems to be no way to change the colour of these icons (they appear to be apart of an image sheet)

![image](https://cloud.githubusercontent.com/assets/12672050/26568241/f2b0f682-4555-11e7-872c-481d3433bc39.png)

**Comment by matt-auckland** [comment]
And with a little css we're fixed.

![image](https://cloud.githubusercontent.com/assets/12672050/26568789/69a8d170-455a-11e7-8a9d-87604e808bee.png)
