### ISSUE TITLE
Support Desk Form

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#55]
Add all the required fields to the support desk form.

- [x] Email
- [x] Name
- [x] Order Number
- [x] Issue Type 
- [x] Message

**Comment by matt-auckland** [comment]
Potential issues for support:
Coins won't send 
Coin's vanished/Coins haven't arrived
Lost Order ID
Order ID not working
Changelly is down (totally/specific wallet is offline/other)
Misc website bug

**Comment by matt-auckland** [comment]
Currently blocked: Need to wait for Freshdesk support to upgrade our trail acc so we can access these features.

**Comment by matt-auckland** [comment]
## Form Preview

![image](https://cloud.githubusercontent.com/assets/12672050/26568169/4d2bb332-4555-11e7-8dda-35fc81b1e611.png)
