### ISSUE TITLE
Submit Send Form and fetch rates from Changelly

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#70]
As a user, once I've input the amount and currency I want to anonymise, i want to have the rates and wait times shown to me.

Fetch rates and wait times from Changelly.

Display to the user.

- [x] Send Form submits to the send page (from either the home page or send page)
- [x] Send Form is populated with the submitted data
- [x] Changelly requested for exchange rates for CURR -> NAV and (NAV * 0.995) -> CURR
- [ ] Changelly requested for transaction times for CURR -> NAV and (NAV * 0.995) -> CURR
- [x] If output currency is NAV, only need to request one set of exchange rates and wait times
- [x] If input and output currency is NAV dont query changelly and show message to use Navtech directly with the NavCoin core wallet
- [x] Things to display the user: confirmation of the action the user is performing, approximate received amount, approximate wait times, fees involved.
- [x] Display general errors in the info box instead of the exchange rates if occurring.
- [ ] Display address, value or currency errors on the form itself, next to the field the error is on.
- [x] Calculate if the amount is too much to send through NAVTech (10k NAV) and show an error to the user with the max amount of that currency we can send at this time.

**Comment by matt-auckland** [comment]
(On Home page): Curr A is selected, Curr B is selected, send is pressed. On the send page we call to changelly (getExchangeAmount) to get an estimate of the conversion.

Rate refreshes on send page when either coin is changed and send button pressed. (or should we show another button? 'refresh exchange rates' perhaps)

**Comment by matt-auckland** [comment]
Inital Setup
- [ ] Navigate to Send Page on Form 'Send'
- [ ] Populate fields with data

Status Component
- [ ] Build 'Status' component and add to page

Changelly Requests
- [ ] Request Changelly for data on exchanges rates
- [ ] Request Changelly for data on exchanges times

Display data to user in Status component.
- [ ] confirmation of the action the user is performing ("You are sending 4 BTC to [addr] in the form of ~1000 DASH")
- [ ] approximate received amount
- [ ] approximate wait times
- [ ] fees involved

Error handling
- [ ]  Transfer amount is over 10,000 Nav err
- [ ]  Transfer amount is under changelly's minimum err
- [ ] User selects Nav to Nav err msg
- [ ] Changelly is down/can't be reached err
- [ ]  Invalid Destination address err
- [ ] If input/output currency is Nav, only request one set of exchange rates (X-> Nav or Nav-> X

**Comment by matt-auckland** [comment]
There's no exposed changelly api point for getting estimated transfer times

**Comment by matt-auckland** [comment]
send-page-data service tests:

- [ ] getData()
- [ ] getDataStream()
- [ ] getDataStatusStream()
- [ ] clearData()
- [ ] checkDataIsSet()
- [ ] validateDataBundle()
- [ ] validateFormData()
- [ ] resetDataBundleErrors()
- [ ] checkAddressIsValid()

- [ ] getMinTransferAmount()
- [ ] getEstimatedExchange()
- [ ] storeData()

**Comment by matt-auckland** [comment]
Pull Request To Dos:
- [ ] Update errors to be an array (send-coins-form + status + send-data-serv)
- [ ] Update how errors are handled on the front end
- [ ] Return error from getMinAmount api route
- [ ] Return error from getExchangeAmount api route
- [ ] Update originCoin/DestCoin to be strings (send-coins-form.component)
- [ ] Update estConvToNav/estConvFromNavto be numbers (send-coins-form.component)
- [ ] Look into changing properties of dataBundle to be decleared on the fly
- [ ] look into removing 'validData' from dataBundle
- [ ] after above update methods that clear the data
- [ ] split nested promises out into their own methods
