### ISSUE TITLE
Hero send coins section

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#8]
As a user i want to be able to easily initialise a Polymorph transaction.

This is the top section of the home page. This should all fit above the fold on our smallest spec resolution. It should be vertically centred in the section. Elements include:

- [x] Logo
- [x] Paragraph text by line
- [x] Amount to send
- [x] Currency to send
- [x] Receiving address
- [x] Currency to receive
- [x] Send button

[N/A] If the user changes the currency to send, the currency to receive should update to match.

Discussion: If the user updates the currency to receive, then changes the currency to send, don't update the currency to receive.

[N/A] Currency drop downs should have the ticker symbol (BTC, LTC, NAV etc) and the full name of the currency (Bitcoin, Litecoin, Nav Coin etc).

Don't worry about validation or submitting the form at this point.

- [x] Pull the currencies from a json file for now.

- [ ] Write some unit tests

**Comment by matt-auckland** [comment]
Adding these features:
```
If the user changes the currency to send, the currency to receive should update to match.

Discussion: If the user updates the currency to receive, then changes the currency to send, don't update the currency to receive.

 Currency drop downs should have the ticker symbol (BTC, LTC, NAV etc) and the full name of the currency (Bitcoin, Litecoin, Nav Coin etc).
```

Is more than the 2 points this story is worth.
