### ISSUE TITLE
Deposit Received Status

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/polymorph#85]
Once we've received the deposit, the order status page should change from the deposit page.

- [x] Should display the status of the order (Received (Confirming), Exchanging (Exchanging, Sending), Sent to NavTech (Finished), Error (Failed, Refunded), Expired)
- [x] Should display a link to the freshdesk in case they have an issue with order.
- [x] Should display an approximate wait time until completed. 
- [x] Should display the order number.
- [x] Updating the fetch order api endpoint to handle these extra statuses

This ticket is not scoped to actually query changelly for the status. Just manually update the status in the database and make sure the front end displays correctly.

Once the order status has changed to Sent to NavTech, we want to display the approximate wait time to either be "< NavTech Time" if outputting NAV, or "< Navtech time + changelly time" if outputting different currency.

**Comment by matt-auckland** [comment]
requires:
- new component for displaying status
- logic for displaying the wait time based on order status
- update old/make new service + backend route for getting order status

Questions:
- Should we display time remaining and an eta? (e.g. ~20 minutes remaining, eta: ~20.45)
